/*
 Dynamsoft JavaScript Library
 Product: Dynamsoft Web Twain
 Web Site: http://www.dynamsoft.com

 Copyright 2021, Dynamsoft Corporation 
 Author: Dynamsoft Support Team
 Module: image io js
 Version: 1.7.2
 @20220110163718.666000+480
 Dynamsoft.WasmEnv.busy() && */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.polyfill=function(a,b,d,e){if(b){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var c=a[e];c in d||(d[c]={});d=d[c]}a=a[a.length-1];e=d[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function d(a){return a instanceof c?a:new c(function(c,b){c(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var c=this;this.asyncExecuteFunction(function(){c.executeBatch_()})}this.batch_.push(a)};var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){e(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var c=0;c<a.length;++c){var b=a[c];a[c]=null;try{b()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var c=this.createResolveAndReject_();try{a(c.resolve,c.reject)}catch(k){c.reject(k)}};c.prototype.createResolveAndReject_=function(){function a(a){return function(f){b||(b=!0,a.call(c,f))}}var c=this,b=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var c=void 0;try{c=a.then}catch(k){this.reject_(k);return}"function"==typeof c?
this.settleSameAsThenable_(c,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,c){if(0!=this.state_)throw Error("Cannot settle("+a+", "+c+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=c;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)f.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var f=new b;c.prototype.settleSameAsPromise_=function(a){var c=this.createResolveAndReject_();a.callWhenSettled_(c.resolve,c.reject)};c.prototype.settleSameAsThenable_=function(a,c){var b=this.createResolveAndReject_();try{a.call(c,b.resolve,b.reject)}catch(l){b.reject(l)}};c.prototype.then=function(a,b){function f(a,c){return"function"==typeof a?function(c){try{d(a(c))}catch(u){g(u)}}:c}var d,g,e=new c(function(a,c){d=a;g=c});this.callWhenSettled_(f(a,d),f(b,g));return e};
c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,c){function b(){switch(d.state_){case 1:a(d.result_);break;case 2:c(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(b):this.onSettledCallbacks_.push(b)};c.resolve=d;c.reject=function(a){return new c(function(c,b){b(a)})};c.race=function(a){return new c(function(c,b){for(var f=$jscomp.makeIterator(a),e=f.next();!e.done;e=f.next())d(e.value).callWhenSettled_(c,
b)})};c.all=function(a){var b=$jscomp.makeIterator(a),f=b.next();return f.done?d([]):new c(function(a,c){function e(c){return function(b){g[c]=b;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,d(f.value).callWhenSettled_(e(g.length-1),c),f=b.next();while(!f.done)})};return c},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(d){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(d||"")+"_"+b++,d)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(d){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var d=a.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,d){d?this.finallyContexts_[d]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,d){try{var e=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(e);if(!e.done)return this.context_.stop_(),e;var c=e.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;d.call(this.context_,c);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function d(b){return a.throw(b)}return new Promise(function(e,c){function f(a){a.done?e(a.value):Promise.resolve(a.value).then(b,d).then(f,c)}f(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var d=0,e={next:function(){if(d<a.length){var c=d++;return{value:b(c,a[c]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.checkStringArgs=function(a,b,d){if(null==a)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,d){var b=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var c=b.length,f=a.length;d=Math.max(0,Math.min(d|0,b.length));for(var g=0;g<f&&d<c;)if(b[d++]!=a[g++])return!1;return g>=f}},"es6","es3");
$jscomp.polyfill("String.prototype.endsWith",function(a){return a?a:function(a,d){var b=$jscomp.checkStringArgs(this,a,"endsWith");a+="";void 0===d&&(d=b.length);d=Math.max(0,Math.min(d|0,b.length));for(var c=a.length;0<c&&0<d;)if(b[--d]!=a[--c])return!1;return 0>=c}},"es6","es3");var Dynamsoft="undefined"!=typeof Dynamsoft?Dynamsoft:("undefined"!=typeof Dynamsoft?window.Dynamsoft:void 0)||{license:"",workerPathPdfR:"",workerPathPdfW:"",workerPathImgcore:""};Dynamsoft.error=Dynamsoft.error||{};
Dynamsoft.error.code=Dynamsoft.error.code||{};Dynamsoft.error.code.wasmBase=-4E3;Dynamsoft.error.code.wasmException=Dynamsoft.error.code.wasmBase-1;Dynamsoft.error.code.wasmNoModule=Dynamsoft.error.code.wasmBase-1;Dynamsoft.error.code.wasmJsBase=-4100;Dynamsoft.error.code.wasmJsObjectNotInit=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsObjectTerminated=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsObjectInitFailed=Dynamsoft.error.code.wasmJsBase-1;
Dynamsoft.error.code.wasmJsNotLoaded=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsInvalidJson=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsWorkerRunException=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsWorkerRunFailed=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsReadFileFailed=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsCoreTaskException=Dynamsoft.error.code.wasmJsBase-1;
Dynamsoft.error.code.wasmJsProcTaskException=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsSavePdfFailed=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsSaveTiffFailed=Dynamsoft.error.code.wasmJsBase-1;
Dynamsoft.conststring={version:"1.7.2",logInfo:"logInfo",logDebug:"logDebug",logAll:"logAll",initPending:"pending",initReady:"ready",initFailed:"failed",imgIO:"imgIO",core:"imgCore",imgProc:"imgProc",pdfR:"pdfReader",pdfW:"pdfWriter",crypto:"crypto",binaryBlobType:"application/octet-stream",wasmExtension:".wasm"};Dynamsoft.constDefine={mainIndex:0,pdfReaderIndex:1,wasmDefHeapSize:28};
Dynamsoft.WasmEnv={wasmJSs:["dynamsoft.imageio_wasm-"+Dynamsoft.conststring.version+".js","dynamsoft.pdfReader_wasm-"+Dynamsoft.conststring.version+".js"],wasmHeap:[{maxHeapSize:300,initHeapSize:280},{maxHeapSize:200,initHeapSize:Dynamsoft.constDefine.wasmDefHeapSize}],moduleNames:[Dynamsoft.conststring.imgIO,Dynamsoft.conststring.crypto,Dynamsoft.conststring.core,Dynamsoft.conststring.imgProc,Dynamsoft.conststring.pdfR,Dynamsoft.conststring.pdfW],imgIO:{name:Dynamsoft.conststring.imgIO,autoLoad:!0,
ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.imageio-",wasmModule:null,wasmJSIndex:Dynamsoft.constDefine.mainIndex},imgCore:{name:Dynamsoft.conststring.core,autoLoad:!0,ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.imagecore-",wasmModule:null,wasmJSIndex:Dynamsoft.constDefine.mainIndex},imgProc:{name:Dynamsoft.conststring.imgProc,autoLoad:!0,ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.imageProc-",wasmModule:null,wasmJSIndex:Dynamsoft.constDefine.mainIndex},
pdfReader:{name:Dynamsoft.conststring.pdfR,autoLoad:!0,ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.pdfReader-",wasmModule:null,wasmJSIndex:Dynamsoft.constDefine.pdfReaderIndex},pdfWriter:{name:Dynamsoft.conststring.pdfW,autoLoad:!0,ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.pdfWriter-",wasmModule:null,wasmJSIndex:Dynamsoft.constDefine.mainIndex},crypto:{name:Dynamsoft.conststring.crypto,autoLoad:!0,ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.crypto-",
wasmModule:null,wasmJSIndex:Dynamsoft.constDefine.mainIndex}};Dynamsoft.WasmEnv.buildWasmFileName=function(a,b,d,e){return a+(e?"sn-":"")+b+d};Dynamsoft.WasmEnv.fetchRetry=function(a,b,d,e){var c=b.retries,f=b.retryDelay;return new Promise(function(g,h){function k(a,c,b){d&&d(e,c);setTimeout(function(){l(++a)},f)}var l=function(f){fetch(a,b).then(function(a){g(a)}).catch(function(a){f<c?k(f,a,null):h(a)})};l(0)})};
Dynamsoft.Enum_ImageType={IT_DIB:-1,IT_RGBA:-2,IT_BGRA:-3,IT_BMP:0,IT_JPG:1,IT_PNG:3,IT_ALL:5};Dynamsoft.Enum_ReturnType={RT_AUTO:-1,RT_BINARY:1,RT_BASE64:2};Dynamsoft.Enum_ErrorMessage={PARAMETER_TYPE_ERROR:"Parameter Type not Supported: ",TIMEOUT:"Timeout no Response: ",FILE_STREAM_ERROR:"File Stream Error: ",WASM_EXCEPTION_ERROR:"An WASM exception occurred."};Dynamsoft.Enum_SimdFlag={SF_DEF:0,SF_ENABLE:1,SF_DISABLE:2};var Dynmasoft=Dynamsoft||{};Dynamsoft.Lib=Dynamsoft.Lib||{};
Dynamsoft.Lib.env=Dynamsoft.Lib.env||{};Dynamsoft.b64ToUint6=function(a){return 64<a&&91>a?a-65:96<a&&123>a?a-71:47<a&&58>a?a+4:43===a?62:47===a?63:0};Dynamsoft.base64DecToArr=function(a,b){a=a.replace(/[^A-Za-z0-9\+\/]/g,"");var d=a.length;b=b?Math.ceil((3*d+1>>>2)/b)*b:3*d+1>>>2;for(var e=new Uint8Array(b),c,f=0,g=0,h=0;h<d;h++)if(c=h&3,f|=Dynamsoft.b64ToUint6(a.charCodeAt(h))<<18-6*c,3===c||1===d-h){for(c=0;3>c&&g<b;c++,g++)e[g]=f>>>(16>>>c&24)&255;f=0}return e};
Dynamsoft.isWasmSupport=function(){try{if("object"===typeof WebAssembly&&"function"===typeof WebAssembly.instantiate){var a=new WebAssembly.Module(Uint8Array.of(0,97,115,109,1,0,0,0));if(a instanceof WebAssembly.Module)return new WebAssembly.Instance(a)instanceof WebAssembly.Instance}}catch(b){}return!1};Dynamsoft.random=function(){return(Date.now()%10086).toString(36).slice(2)+Math.random().toString(36).slice(2)};
Dynamsoft.readFile=function(a){return new Promise(function(b,d){var e=Object.prototype.toString.call(a);if("[object String]"===e)0===a.indexOf("blob:")||0<a.indexOf(".jpg")||0<a.indexOf(".jpeg")||0<a.indexOf(".png")||0<a.indexOf(".bmp")||0<a.indexOf(".dib")||0<a.indexOf(".pdf")||0<a.indexOf(".tiff")||0<a.indexOf(".tif")?fetch(a,{mode:"cors"}).then(function(a){return a.arrayBuffer()}).then(function(a){return b(a)}).catch(function(a){return Promise.reject(a)}):d("Error url: Can not read the file URL");
else if("[object Blob]"===e||"[object FileList]"===e||"[object File]"===e){d=a;if("[object FileList]"===e||"[object File]"===e)d=a[0]?a[0]:a;var c=new FileReader;c.readAsArrayBuffer(d);c.onload=function(){b(c.result)}}else"[object ArrayBuffer]"===e||"[object Uint8ClampedArray]"===e?b(a):d("Not support source type: "+e)})};
Dynamsoft.base64Decode=function(a){function b(a){var c=[],b=a.length,d;for(d=0;d<b;d++){var e=a.charCodeAt(d);if(0==(e>>7&255))c.push(a.charAt(d));else if(6==(e>>5&255)){var k=a.charCodeAt(++d);e=(e&31)<<6;k&=63;e|=k;c.push(String.fromCharCode(e))}else if(14==(e>>4&255)){k=a.charCodeAt(++d);var l=a.charCodeAt(++d);e=e<<4|k>>2&15;k=(k&3)<<6|l&63;e=(e&255)<<8|k;c.push(String.fromCharCode(e))}}return c.join("")}var d=[-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,62,-1,-1,-1,63,52,53,54,55,56,57,58,59,60,61,-1,-1,-1,-1,-1,-1,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,-1,-1,-1,-1,-1,-1,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,-1,-1,-1,-1,-1];return function(a){for(var c=[],f=0,e=a.length,h,k;f<e;){do h=d[a.charCodeAt(f++)&255];while(f<e&&-1==h);if(-1==h)break;do k=d[a.charCodeAt(f++)&255];while(f<e&&-1==k);if(-1==k)break;c.push(String.fromCharCode(h<<
2|(k&48)>>4));do{h=a.charCodeAt(f++)&255;if(61==h)return b(c.join(""));h=d[h]}while(f<e&&-1==h);if(-1==h)break;c.push(String.fromCharCode((k&15)<<4|(h&60)>>2));do{k=a.charCodeAt(f++)&255;if(61==k)return b(c.join(""));k=d[k]}while(f<e&&-1==k);if(-1==k)break;c.push(String.fromCharCode((h&3)<<6|k))}return b(c.join(""))}(a)};Dynamsoft.WasmEnv=Dynamsoft.WasmEnv||{};Dynamsoft.WasmEnv.lastInstanceId=0;Dynamsoft.WasmEnv.worker={maxWorkers:1,liveTime:60};
Dynamsoft.WasmEnv.resourceDir=Dynamsoft.DWT.ResourcesPath+"/src/";Dynamsoft.WasmEnv.logLevel=Dynamsoft.DWT.Debug?Dynamsoft.conststring.logDebug:0;Dynamsoft.WasmEnv.logFunc=null;Dynamsoft.WasmEnv.productKey="";Dynamsoft.WasmEnv.licMode=0;Dynamsoft.WasmEnv.uuid="";Dynamsoft.WasmEnv.fetchOptions={mode:"cors",credentials:"same-origin",retries:3,retryDelay:500};Dynamsoft.WasmEnv.simdFlag=Dynamsoft.Enum_SimdFlag.SF_DEF;Dynamsoft.WasmEnv.useFastcompEdition=!1;
Dynamsoft.WasmEnv.log=function(a,b){var d=Dynamsoft.WasmEnv;d.logLevel===b&&("function"===typeof d.logFunc?d.logFunc(a):console.log(a))};Dynamsoft.WasmEnv.clear=function(a){for(var b=$jscomp.makeIterator(Dynamsoft.WasmEnv.moduleNames),d=b.next();!d.done;d=b.next())if(d=d.value,Dynamsoft.WasmEnv[d].wasmJSIndex==a||void 0==a)Dynamsoft.WasmEnv[d].status="",delete Dynamsoft.WasmEnv[d].error};
Dynamsoft.WasmEnv.setLoglevel=function(a,b){Dynamsoft.WasmEnv.logLevel=1===a?Dynamsoft.conststring.logDebug:0;Dynamsoft.WasmEnv.logFunc=b};
Dynamsoft.WorkerHandler=function(a,b){function d(a){e.terminated=!0;e.options.log("[js]["+Date.now()/1E3+"] worker error "+JSON.stringify(a),e.context);e.terminating&&e.terminationHandler&&e.terminationHandler(e);e.terminating=!1;e.cancelAllTasks()}var e=this;this.options=b||{};this.script=a;this.worker=function(a){if("function"!==typeof Worker&&("object"!==typeof Worker||"function"!==typeof Worker.prototype.constructor))throw Error("Web Workers not supported");a=new Worker(a);a.on=function(a,c){this.addEventListener(a,
function(a){c(a.data)})};a.send=function(a){if(void 0!=a&&void 0!=a.params&&void 0!=a.params.input){var c=Object.prototype.toString.call(a.params.input);if("[object Array]"===Object.prototype.toString.call(a.params.input)){if(c=Object.prototype.toString.call(a.params.input[0]),"[object ArrayBuffer]"===c||"[object Uint8ClampedArray]"===c||"[object Uint8Array]"===c){this.postMessage(a,[void 0!=a.params.input[0].buffer?a.params.input[0].buffer:a.params.input[0]]);return}}else if("[object ArrayBuffer]"===
c||"[object Uint8ClampedArray]"===c||"[object Uint8Array]"===c){this.postMessage(a,[void 0!=a.params.input.buffer?a.params.input.buffer:a.params.input]);return}}this.postMessage(a)};return a}(this.script);this.requestQueue=[];this.terminated=this.terminating=!1;e.tasks=Object.create(null);this.objectToError=function(a){for(var c=Error(""),b=Object.keys(a),d=0;d<b.length;d++)c[b[d]]=a[b[d]];return c};this.dispatchQueuedRequests=function(){e.requestQueue.forEach(e.worker.send.bind(e.worker));e.requestQueue=
[]};this.logDebug=function(a){Dynamsoft.WasmEnv.logLevel===Dynamsoft.conststring.logDebug&&"function"===typeof e.options.log&&e.options.log("[js]["+Date.now()/1E3+"] "+a,e.context)};this.worker.on("message",function(a){"function"===typeof e.options.log&&e.options.log(a.log?a.log:a,e.context);if("string"===typeof a&&"ready"===a)e.worker.ready=!0,e.dispatchQueuedRequests();else if(!a.log){if("object"===typeof a){var b=a.result;"object"===typeof b?(void 0!=b.errorCode&&(b.code=b.errorCode,delete b.errorCode),
void 0!=b.errorMessage&&(b.message=b.errorMessage,delete b.errorMessage)):"string"===typeof b&&(b=b.replace('"errorCode"','"code"'),b=b.replace("'errorCode'","'code'"),b=b.replace('"errorMessage"','"message"'),b=b.replace("'errorMessage'","'message'"),a.result=b);void 0!=a.memSize&&(e.memSize=a.memSize)}b=a.id;var c=e.tasks[b];void 0!==c?(delete e.tasks[b],e.logDebug(a.func+" received"),!0===e.terminating&&e.terminate(),"loadWasm"===a.func&&void 0!=a.result&&(e.worker.wasmReady=!0,e.dispatchQueuedRequests()),
a.error?c.resolver.reject(e.objectToError(a.error)):a.result&&c.resolver.resolve(a.result)):"loadWasm"===a.func&&void 0!=a.result&&Dynamsoft.WasmEnv._handleWasmLoad(a.result,e)}});this.worker.on("error",d);this.worker.on("exit",function(a,b){a="Worker terminated Unexpectedly\n exitCode: `"+(a+"`\n signalCode: `")+(b+"`\n script: `")+(e.script+"`\n");d(Error(a))});this.terminated=this.terminating=!1;this.terminationHandler=null;this.lastTaskId=0};
Dynamsoft.WorkerHandler.prototype.exec=function(a,b,d){d||(d={},d.promise=new Promise(function(a,b){d.resolve=a;d.reject=b}));var e=++this.lastTaskId;this.tasks[e]={id:e,resolver:d};b={id:e,func:a,params:b};Dynamsoft.WasmEnv.logLevel===Dynamsoft.conststring.logDebug&&(b.params.logLevel=Dynamsoft.conststring.logDebug,this.logDebug(a+" send"));this.terminated?d.reject(Error("Worker is terminated")):this.terminating?d.reject(Error("Worker is terminating")):this.worker.wasmReady||this.worker.ready&&"loadWasm"===
a?this.worker.send(b):this.requestQueue.push(b);return d.promise};Dynamsoft.WorkerHandler.prototype.busy=function(){return 0<this.howManyTasks()};Dynamsoft.WorkerHandler.prototype.howManyTasks=function(){return Object.keys(this.tasks).length};Dynamsoft.WorkerHandler.prototype.cancelAllTasks=function(a){for(var b in this.tasks)void 0!==this.tasks[b]&&this.tasks[b].resolver.reject(Error(a));this.tasks=Object.create(null)};
Dynamsoft.WorkerHandler.prototype.alive=function(){return this.terminating||this.terminated?!1:!0};
Dynamsoft.WorkerHandler.prototype.terminate=function(a,b){this.logDebug("worker terminate "+a);a&&this.cancelAllTasks("Worker has been terminated");"function"===typeof b&&(this.terminationHandler=b);if(this.busy())this.terminating=!0;else{if(this.worker){if("function"===typeof this.worker.terminate)this.worker.terminate();else throw Error("Failed to terminate worker");this.worker=null}this.terminating=!1;this.terminated=!0;this.terminationHandler&&this.terminationHandler(this)}};
Dynamsoft.WorkerHandler.prototype.setLogCallback=function(a,b){this.options.log=a;this.context=b};
Dynamsoft.WorkerPool=function(a,b,d,e){var c=this;this.workers=[];this.options=a;this.maxWorkers=1;this.script=this.options.resourceDir+d;this.ready=!1;this.pdfReaderInstance=null;this.terminated=!1;this.wasmLoaderPromise=Object.create(null);this.poolIndex=e;this.crossScript=!1;this._getMaxWorkers=function(){var a=2;"hardwareConcurrency"in self.navigator&&(a=self.navigator.hardwareConcurrency);return Math.max(Math.min(c.options.worker.maxWorkers,Math.max(c.options.worker.maxWorkers,a/2)),1)};this._logAll=
function(a){Dynamsoft.WasmEnv.log(a,Dynamsoft.conststring.logAll)};this._log=function(a,b){Dynamsoft.WasmEnv.log(a,Dynamsoft.conststring.logDebug)};this._createWorker=function(){c.ready&&(c.maxWorkers=c._getMaxWorkers());var a=c.workers;if(a.length<c.maxWorkers){var b=new Dynamsoft.WorkerHandler(c.script);a.push(b);b.id=a.length;b.module={};b.module.modulesInfo=[];b.instances=Object.create(null);b.setLogCallback(this._log,c);c._logAll(a);c.log("get new worker "+b.id+" succeed!");return b}return null};
this._getContainedModuleWorkers=function(a){c._removeTerminatedWorker();var b=c.workers;c._logAll(b);for(var d=[],f=$jscomp.makeIterator(b),e=f.next();!e.done;e=f.next())e=e.value,!e.module.modulesInfo[a.name]||e.busy()&&b.length<c.maxWorkers||d.push(e);c._logAll("get workers for module "+a.name);c._logAll(d);return d};this._checkWorkerValid=function(){c._removeTerminatedWorker();0==c.workers.length&&c.data&&(c.log("no worker ready, reinit"),c.crossScript?c._initAsync(c.data):c._init(c.data))};this._getIdleWorker=
function(){c._removeTerminatedWorker();for(var a=$jscomp.makeIterator(c.workers),b=a.next();!b.done;b=a.next())if(b=b.value,!1===b.busy())return b;return c._createWorker()};this._busy=function(){c._removeTerminatedWorker();for(var a=$jscomp.makeIterator(c.workers),b=a.next();!b.done;b=a.next())if(b.value.busy())return!0;return!1};this._removeTerminatedWorker=function(){c.workers=c.workers.filter(function(a){return!a.terminated})};this._getWorkerByIntanceId=function(a,b){c._logAll("_getWorkerByIntanceId");
c._logAll(a);for(var d=9007199254740991,e=null,f=$jscomp.makeIterator(a),g=f.next();!g.done;g=f.next())if(g=g.value,void 0!=g.instances[b]){e=g;break}else{var m=g.howManyTasks();m<d&&(e=g,d=m)}if(e)return e.instances[b]="",c._logAll(a),c.log("get worker "+b+" in "+e.id+" succeed!"),e;c._logAll("_getWorkerByIntanceId: no suitable worker");return null};this._initWorkerInner=function(a,b,d){try{b.params&&(b.params.resourceDir=this.resourceDir,b.params.fetchOptions=Dynamsoft.WasmEnv.fetchOptions);for(var e=
$jscomp.makeIterator(b.params.module.modulesInfo),f=e.next();!f.done;f=e.next())Dynamsoft.WasmEnv[f.value.name].status=Dynamsoft.conststring.initPending;a.exec(b.func,b.params).then(function(b){void 0===b.code||b.modules?Dynamsoft.WasmEnv._handleWasmLoad(b,a):c.log(b);d()}).catch(function(a){c.log(a);d()})}catch(r){c.log(r),d()}};this._removeInstanceInWorker=function(a,b){var d=c.workers;c._logAll("removeInstanceInWorker");c._logAll(d);for(var e=$jscomp.makeIterator(d),f=e.next();!f.done;f=e.next())if(f=
f.value,f===a){void 0!=f.instances[b]?(delete f.instances[b],c._logAll(d),c.log("removeInstanceInWorker "+b+" in "+f.id+" succeed!")):c.log("not found instance "+b);break}};this._hasInstanceInWorker=function(){for(var a=$jscomp.makeIterator(c.workers),b=a.next();!b.done;b=a.next())if(0!=Object.keys(b.value.instances).length)return!0;return null!=c.pdfReaderInstance};this._getWorker=function(a,b){if(Dynamsoft.WasmEnv[a.name].status==Dynamsoft.conststring.initPending)return this._checkWorkerValid(),
null;var d=c._getContainedModuleWorkers(a);if(0!=d.length)return c._getWorkerByIntanceId(d,b);if(d=c._getIdleWorker()){if(d.module.modulesInfo[a.name])return d;c.log("_getWorker: try to recreate worker "+b);a={id:0,func:"loadWasm",params:{priority:0,key:c.options.productKey,licMode:Dynamsoft.WasmEnv.licMode,uuid:Dynamsoft.WasmEnv.uuid,module:{modulesInfo:[],poolIndex:c.poolIndex,useFastcompEdition:Dynamsoft.WasmEnv.useFastcompEdition}}};b=$jscomp.makeIterator(Dynamsoft.WasmEnv.moduleNames);for(var e=
b.next();!e.done;e=b.next())e=e.value,void 0!=Dynamsoft.WasmEnv[e].poolIndex&&Dynamsoft.WasmEnv[e].poolIndex==c.poolIndex&&a.params.module.modulesInfo.push({name:e,ver:Dynamsoft.WasmEnv[e].ver,wasmModule:Dynamsoft.WasmEnv[e].wasmModule,poolIndex:Dynamsoft.WasmEnv[e].poolIndex,useSimd:Dynamsoft.WasmEnv[e].useSimd});c._initWorkerInner(d,a,function(){})}return null};this._init=function(a){var b=c._createWorker();b&&(b.setLogCallback(function(a,b){b.log(a)},c),a.params.callback=null,c._initWorkerInner(b,
a,function(a){c.maxWorkers=c._getMaxWorkers();c.ready=!0}))};this._initAsync=function(a){var b=this,d;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){if(1==e.nextAddress)return d=c,e.yield(Dynamsoft.WasmEnv.fetchRetry(c.script,Dynamsoft.WasmEnv.fetchOptions,b._log,b).then(function(a){return a.blob()}).then(function(a){return URL.createObjectURL(a)}),2);d.script=e.yieldResult;c._init(a);e.jumpToEnd()})};this._getPath=function(){this.script.startsWith("http://")||this.script.startsWith("https://")?
this.resourceDir=this.options.resourceDir:this.options.resourceDir.startsWith("/")?null!=location.origin&&(this.resourceDir=location.origin+this.options.resourceDir):null!=location.href&&(this.resourceDir=location.href.substring(0,location.href.lastIndexOf("/")+1)+this.options.resourceDir);this.resourceDir.endsWith("/")||(this.resourceDir+="/");e==Dynamsoft.constDefine.mainIndex&&Dynamsoft.WasmEnv.useFastcompEdition&&(this.resourceDir+="fastcomp/",this.script=this.resourceDir+d)};this._getPath();
b&&0<b.params.module.modulesInfo.length?(!this.script.startsWith("http://")&&!this.script.startsWith("https://")||this.script.startsWith(location.origin)||(this.crossScript=!0),this.data=b,this.crossScript?this._initAsync(b):this._init(b)):(c.maxWorkers=c._getMaxWorkers(),c.ready=!0)};
Dynamsoft.WorkerPool.prototype.getWorker=function(a,b){if(!this.ready)return null;var d=a.name===Dynamsoft.WasmEnv.pdfReader.name;if(d&&this.pdfReaderInstance)return null;if((a=this._getWorker(a,b))&&d){if(this.pdfReaderInstance)return this._removeInstanceInWorker(a,b),null;this.pdfReaderInstance=b}return a};
Dynamsoft.WorkerPool.prototype.removeInstanceInWorker=function(a,b,d,e){this._removeInstanceInWorker(b,d);a.name===Dynamsoft.WasmEnv.pdfReader.name&&this.pdfReaderInstance&&(this.pdfReaderInstance=null);e&&b&&void 0!=b.memSize&&(a=1048576*Dynamsoft.WasmEnv.wasmHeap[this.poolIndex].maxHeapSize,Dynamsoft.WasmEnv.log("current memSize="+b.memSize+", max="+a,Dynamsoft.conststring.logDebug),b.memSize>a&&0!=a&&!this._hasInstanceInWorker()&&(Dynamsoft.WasmEnv.log("reload wasm auto",Dynamsoft.conststring.logDebug),
Dynamsoft.WasmEnv.load(void 0,void 0,void 0,this.poolIndex)))};Dynamsoft.WorkerPool.prototype.log=function(a){Dynamsoft.WasmEnv.log(a,Dynamsoft.conststring.logDebug)};
Dynamsoft.WorkerPool.prototype.terminate=function(a){Dynamsoft.WasmEnv.log("worker pool terminate "+a,Dynamsoft.conststring.logDebug);this.terminated=!0;var b=[],d=this.workers.slice();this.workers=[];d.forEach(function(d){var c={};c.promise=new Promise(function(a,b){c.resolve=a;c.reject=b});b.push(c.promise);d.terminate(a,function(a){c.resolve(a)})});return Promise.all(b)};
Dynamsoft.WorkerPool.prototype.getMemoryUsed=function(){for(var a=[],b=0,d=$jscomp.makeIterator(this.workers),e=d.next();!e.done;e=d.next())(e=e.value)&&void 0!=e.memSize&&(a[b++]=e.memSize);return a};Dynamsoft.WasmEnv.loadPdfReader=function(a,b,d){Dynamsoft.WasmEnv.load(a,b,d,Dynamsoft.constDefine.pdfReaderIndex)};Dynamsoft.WasmEnv.loadMain=function(a,b,d){Dynamsoft.WasmEnv.load(a,b,d,Dynamsoft.constDefine.mainIndex)};
Dynamsoft.WasmEnv.load=function(a,b,d,e){Dynamsoft.WasmEnv.unload(e);Dynamsoft.WasmEnv.productKey=void 0!=a?a:Dynamsoft.WasmEnv.productKey;void 0!=b&&(Dynamsoft.WasmEnv.licMode=b?1:0);Dynamsoft.WasmEnv.uuid=void 0!=d?d:Dynamsoft.WasmEnv.uuid;Dynamsoft.WasmEnv.licenseInfo=void 0;Dynamsoft.WasmEnv.loadingPromise={};Dynamsoft.WasmEnv.loadingPromise.promise=new Promise(function(a,b){Dynamsoft.WasmEnv.loadingPromise.resolve=a;Dynamsoft.WasmEnv.loadingPromise.reject=b});var c=Dynamsoft.WasmEnv;c.clear(e);
void 0===Dynamsoft.WorkerPool.Instances&&(Dynamsoft.WorkerPool.Instances=[]);void 0!=e?Dynamsoft.WorkerPool.Instances[e]=null:Dynamsoft.WorkerPool.Instances=[];for(b=0;b<c.wasmJSs.length;b++)if(void 0==e||e==b)d={id:0,func:"loadWasm",params:{priority:0,key:a,licMode:Dynamsoft.WasmEnv.licMode,uuid:Dynamsoft.WasmEnv.uuid,module:{modulesInfo:[],poolIndex:b,useFastcompEdition:Dynamsoft.WasmEnv.useFastcompEdition},callback:function(a){c.logLevel===Dynamsoft.conststring.logDebug&&("function"===typeof c.logFunc?
c.logFunc(a):console.log(a))}}},c.imgCore.autoLoad&&c.imgCore.wasmJSIndex==b&&(d.params.module.modulesInfo.push({name:c.imgIO.name,ver:c.imgIO.ver,wasmModule:c.imgIO.wasmModule,poolIndex:b}),c.imgIO.poolIndex=b,1===Dynamsoft.WasmEnv.licMode&&(d.params.module.modulesInfo.push({name:c.crypto.name,ver:c.crypto.ver,wasmModule:c.crypto.wasmModule,poolIndex:b}),c.crypto.poolIndex=b)),(c.imgCore.autoLoad||c.imgCore.wasmModule)&&c.imgCore.wasmJSIndex==b&&(d.params.module.modulesInfo.push({name:c.imgCore.name,
ver:c.imgCore.ver,wasmModule:c.imgCore.wasmModule,poolIndex:b}),c.imgCore.poolIndex=b),(c.imgProc.autoLoad||c.imgProc.wasmModule)&&c.imgProc.wasmJSIndex==b&&(c.imgProc.useSimd=Dynamsoft.WasmEnv.getUseSimd(),d.params.module.modulesInfo.push({name:c.imgProc.name,ver:c.imgProc.ver,wasmModule:c.imgProc.wasmModule,poolIndex:b,useSimd:c.imgProc.useSimd}),c.imgProc.poolIndex=b),(c.pdfReader.autoLoad||c.pdfReader.wasmModule)&&c.pdfReader.wasmJSIndex==b&&(d.params.module.modulesInfo.push({name:c.pdfReader.name,
ver:c.pdfReader.ver,wasmModule:c.pdfReader.wasmModule,poolIndex:b}),c.pdfReader.poolIndex=b),(c.pdfWriter.autoLoad||c.pdfWriter.wasmModule)&&c.pdfWriter.wasmJSIndex==b&&(d.params.module.modulesInfo.push({name:c.pdfWriter.name,ver:c.pdfWriter.ver,wasmModule:c.pdfWriter.wasmModule,poolIndex:b}),c.pdfWriter.poolIndex=b),Dynamsoft.WorkerPool.Instances[b]=0!=d.params.module.modulesInfo.length?new Dynamsoft.WorkerPool(c,d,c.wasmJSs[b],b,Dynamsoft.WasmEnv.maxHeapSize,Dynamsoft.WasmEnv.initH):null};
Dynamsoft.WasmEnv.unloadMain=function(){return Dynamsoft.WasmEnv.unload(Dynamsoft.constDefine.mainIndex)};Dynamsoft.WasmEnv.unloadPdfReader=function(){return Dynamsoft.WasmEnv.unload(Dynamsoft.constDefine.pdfReaderIndex)};
Dynamsoft.WasmEnv.getUseSimd=function(){if(Dynamsoft.WasmEnv.useFastcompEdition)return!1;if(Dynamsoft.WasmEnv.simdFlag===Dynamsoft.Enum_SimdFlag.SF_DEF){if(void 0!=navigator.userAgentData&&void 0!=navigator.userAgentData.brands)for(var a=$jscomp.makeIterator(navigator.userAgentData.brands),b=a.next();!b.done;b=a.next())if(b=b.value,b.brand&&("Chromium"==b.brand||"Google Chrome"==b.brand)&&b.version&&94<=parseInt(b.version,10))return!0}else if(Dynamsoft.WasmEnv.simdFlag===Dynamsoft.Enum_SimdFlag.SF_ENABLE)return!0;
return!1};Dynamsoft.WasmEnv.unload=function(a){var b=Dynamsoft.WorkerPool.Instances;if(void 0!=b){if(void 0!=a)return b[a].terminate(!0);a=[];b=$jscomp.makeIterator(b);for(var d=b.next();!d.done;d=b.next())a.push(d.value.terminate(!0));return a}return Promise.resolve()};Dynamsoft.WasmEnv.getWorkerPool=function(a){var b=Dynamsoft.WorkerPool.Instances;return b?(a=b[a],a.terminated?null:a):null};
Dynamsoft.WasmEnv.busy=function(a){var b=Dynamsoft.WorkerPool.Instances;if(b){if(void 0!=a)return b[a].busy();a=$jscomp.makeIterator(b);for(b=a.next();!b.done;b=a.next())if(b.value._busy())return!0}return!1};
Dynamsoft.WasmEnv._handleWasmLoad=function(a,b){Dynamsoft.WasmEnv.log("handleWasmLoad:",Dynamsoft.conststring.logDebug);Dynamsoft.WasmEnv.log(a,Dynamsoft.conststring.logDebug);if("object"!=typeof a||void 0==a.modules)"object"===typeof a&&Dynamsoft.WasmEnv.loadingPromise.reject({code:a.code,message:a.message});else{for(var d=$jscomp.makeIterator(a.modules),e=d.next();!e.done;e=d.next())e=e.value,a.code?(Dynamsoft.WasmEnv[e.name].error={code:a.code,message:a.message},b.module.modulesInfo[e.name]=!1):
(delete Dynamsoft.WasmEnv[e.name].error,Dynamsoft.WasmEnv[e.name].status=Dynamsoft.conststring.initReady,Dynamsoft.WasmEnv[e.name].wasmModule=e.wasmModule,b.module.modulesInfo[e.name]=!0);a.licenseInfo&&(a=a.licenseInfo,"string"===typeof a&&(a=JSON.parse(a),Dynamsoft.WasmEnv.licenseInfo=a),Dynamsoft.WasmEnv.loadingPromise.resolve(a));void 0!=Dynamsoft.WasmEnv.imgIO.error&&Dynamsoft.WasmEnv.loadingPromise.reject(Dynamsoft.WasmEnv.imgIO.error)}};
Dynamsoft.ImageIoBase=function(a,b,d,e){var c=this;this.moduleInfo=b;this.name=this.moduleInfo.name;this.outputType=Dynamsoft.Enum_ImageType.IT_JPG;this.inputType=Dynamsoft.Enum_ImageType.IT_ALL;this.tiffFormat=0;this.jpegQuality=80;this.tasksQueue=[];this.worker=null;this.lastTaskId=0;this.logFunc=d;this.context=e;this.instanceId=++Dynamsoft.WasmEnv.lastInstanceId;this.timer=null;this.nv=JSON.parse(JSON.stringify(Dynamsoft.navInfo));this.mb=Dynamsoft.Lib.env.bMobile;this.dm=location.origin;this.initStatus=
"";this.terminated=!1;this.license=a?a:Dynamsoft.license;this.license||(this.license="");this.licMode=Dynamsoft.WasmEnv.licMode;this.uuid=Dynamsoft.WasmEnv.uuid;this._getWorker=function(){c.timer&&clearTimeout(c.timer);if(c.worker&&c.worker.alive())return c.worker;var a=Dynamsoft.WasmEnv.getWorkerPool(c.moduleInfo.poolIndex);if(a){c.worker=a.getWorker(c.moduleInfo,c.instanceId);if(c.worker&&c.worker.alive())0<c.tasksQueue.length&&c._dispatchQueuedTasks();else{if(Dynamsoft.WasmEnv[c.name].error)return c._cancelAllTasks(Dynamsoft.error.code.wasmJsNotLoaded,
Dynamsoft.WasmEnv[c.name].error),c.worker;0<c.tasksQueue.length&&(c.timer=setTimeout(c._getWorker,50))}return c.worker}c._cancelAllTasks(Dynamsoft.error.code.wasmJsNotLoaded,"wasm env not loaded")};this._dispatchQueuedTasks=function(){c._logAll(c.tasksQueue,c);if(c.worker&&c.worker.alive()){if(0<c.tasksQueue.length){var a=c.tasksQueue[0];if(c.initStatus===Dynamsoft.conststring.initReady||"init"===a.func)delete c.tasksQueue[0],c.tasksQueue.splice(0,1),c._exec(a)}}else c.worker&&!c.worker.alive()&&
0<c.tasksQueue.length&&"init"!=c.tasksQueue[0].func?(c.worker=null,c._init()):0<c.tasksQueue.length&&c._getWorker()};this._log=function(a,b){"function"===typeof b.logFunc?b.logFunc(a,b.context):Dynamsoft.WasmEnv.log(a,Dynamsoft.conststring.logDebug)};this._logAll=function(a,b){Dynamsoft.WasmEnv.logLevel===Dynamsoft.conststring.logAll&&this._log(a,b)};this._handleReject=function(a,b,c){var d=b;"object"!=typeof d&&(d={},d.code=c,d.message=b);return this.terminated?a.resolve(d):a.reject(d)};this._handleBasicResult=
function(a,b){delete a.code;delete a.message;return a};this._handleBooleanResult=function(a,b){return!0};this._createImageResult=function(a,b,c){return c?void 0!=b?new Blob([a],{type:b}):new Blob([a]):a};this._handleImageData=function(a,b){if("object"===typeof a.imageData)if(void 0!=a.imageCount&&1<a.imageCount)for(var c=0;c<a.imageCount;c++)a.imageData[c]=b.context._createImageResult(a.imageData[c],a.blobType,b.params.returnBlob);else a.imageData=b.context._createImageResult(a.imageData,a.blobType,
b.params.returnBlob);"object"===typeof a.pdfData&&(a.pdfData=b.context._createImageResult(a.pdfData,a.blobType,b.params.returnBlob));return a};this._handleResult=function(a,b){a=b.context._getResult(a);void 0===a.code||!a.code&&"Successful."===a.message?(a=b.handleResult(a,b),c._dispatchQueuedTasks(),b=b.resolve,b(a)):(a={code:a.code,message:a.code===Dynamsoft.error.code.wasmException?Dynamsoft.Enum_ErrorMessage.WASM_EXCEPTION_ERROR:a.message},this.terminated?b.resolve(a):b.reject(a))};this._getResult=
function(a){try{return"string"===typeof a?JSON.parse(a):a}catch(g){return a}};this._exec=function(a){var b=c.worker;b.setLogCallback(c._log,c);c._logAll(a,c);try{b.exec(a.func,a.params).then(function(b){c._log(b,c);c._handleResult(c._getResult(b),a)}).catch(function(b){c._log(b,c);c._dispatchQueuedTasks();var d=b;"object"===typeof b&&void 0!=b.message&&(d=b.message);b={code:Dynamsoft.error.code.wasmJsWorkerRunFailed,message:d};c.terminated?a.resolve(b):a.reject(b)})}catch(h){c._dispatchQueuedTasks(),
c._log(h,c),b={code:Dynamsoft.error.code.wasmJsWorkerRunException,message:h.message,stack:h.stack},c.terminated?a.resolve(b):a.reject(b)}};this._cancelAllTasks=function(a,b){for(var d=$jscomp.makeIterator(c.tasksQueue),e=d.next();!e.done;e=d.next())if(e=e.value,void 0!==e){var f={code:a,message:b};c.terminated?e.resolve(f):e.reject(f)}c.tasksQueue=[]};this._createTask=function(a,b,c){var d={id:++this.lastTaskId};d.promise=new Promise(function(a,b){d.resolve=a;d.reject=b});d.func=a;d.params={moduleName:this.name,
insId:this.instanceId,fetchOptions:Dynamsoft.WasmEnv.fetchOptions,initHeapSize:Dynamsoft.WasmEnv.wasmHeap[this.moduleInfo.poolIndex].initHeapSize};d.context=this;d.handleResult="undefined"!==typeof c&&c?c:this._handleBasicResult;d.params.input="undefined"!==typeof b&&b?b:"";d.params.returnType="";d.params.returnBlob=!0;return d};this._addTask=function(a,b){""===this.initStatus?a.reject({code:Dynamsoft.error.code.wasmJsObjectNotInit,message:this.terminated?"object has been disposed":"object not init"}):
this.initStatus===Dynamsoft.conststring.initFailed?a.reject({code:Dynamsoft.error.code.wasmJsObjectInitFailed,message:c.initError}):(b?c.tasksQueue.unshift(a):c.tasksQueue.push(a),c._dispatchQueuedTasks());return a.promise};this._init=function(){var a=this._createTask("init");a.params.key=this.license;a.params.uuid=this.uuid;a.params.licMode=this.licMode;a.params.val={nv:this.nv,mb:this.mb,dm:this.dm};a.handleResult=function(a,b){b.context.initStatus=Dynamsoft.conststring.initReady;return a};this.initStatus=
Dynamsoft.conststring.initPending;this._addTask(a,!0);a.promise.then(function(a){c._log(c.name+" init return: ",c);c._log(a,c)}).catch(function(a){c.initStatus=Dynamsoft.conststring.initFailed;c.initError=a.message;c._log(c.name+" init failed",c);c._log(a,c);c._cancelAllTasks(Dynamsoft.error.code.wasmJsObjectInitFailed,a.message)})};this._destroy=function(){var a=this._createTask("destroy");this._addTask(a);return a.promise};this._terminate=function(a){var b=this._destroy();this.terminated=!0;var d=
Dynamsoft.WasmEnv.getWorkerPool(c.moduleInfo.poolIndex);d&&d.removeInstanceInWorker(c.moduleInfo,c.worker,c.instanceId,a);b.then(function(a){c.worker=null;c._log(c.name+" destroy return: ",c);c._log(a,c)}).catch(function(a){c.worker=null;c._log(c.name+" destroy failed",c);c._log(a,c)});this.initStatus=""};this._readFile=function(a,b){return new Promise(function(d,e){Dynamsoft.readFile(a).then(function(a){d(a)},function(a){c._handleReject(b,a,Dynamsoft.error.code.wasmJsReadFileFailed)}).catch(function(a){c._handleReject(b,
a,Dynamsoft.error.code.wasmJsReadFileFailed)})})};this._init()};Dynamsoft.ImageIoBase.prototype.terminate=function(a){this._terminate(void 0!=a?a:!0)};
Dynamsoft.ImageIoBase.prototype.downloadData=function(a,b,d,e){a=a?a:Date.now()+"";return(new Promise(function(c,f){if(b){if("base64"===d){var g=Dynamsoft.base64DecToArr(b).buffer;g=new Blob([g],{type:"pdf"==e?"application/pdf":"jpg"==e?"image/jpeg":"image/"+e});g=URL.createObjectURL(g)}else"blob"===d?g=b:f(Dynamsoft.Enum_ErrorMessage.FILE_STREAM_ERROR+"Please read/write image or get page before download!");a=a+"."+e;window.navigator.msSaveBlob&&fetch(g).then(function(a){return a.arrayBuffer()}).then(function(b){b=
new Blob([b]);window.navigator.msSaveOrOpenBlob(b,a);c(a)});f=document.createElement("a");f.href=g;f.download=a;f.click();c(a)}else f(Dynamsoft.Enum_ErrorMessage.FILE_STREAM_ERROR+"Please read/write image or get page before download!")})).catch(function(a){return Promise.reject(a)})};
Dynamsoft.Imagecore=function(a,b,d){a=a?a:Dynamsoft.WasmEnv.productKey;Dynamsoft.ImageIoBase.call(this,a,Dynamsoft.WasmEnv.imgCore,b,d);this.saveImageInner=function(a,b,d,g,h,k,l,r,m,t){var c=this;b=void 0!=b?b:this.inputType;d=void 0!=d?d:0;g=void 0!=g?g:0;h=void 0!=h?h:24;k=void 0!=k?k:96;l=void 0!=l?l:96;r=void 0!=r?r:this.outputType;m=void 0!=m?m:this.jpegQuality;t=void 0!=t?t:Dynamsoft.Enum_ReturnType.RT_AUTO;var e=c._createTask("SaveImage");c._readFile(a,e).then(function(a){e.params.input=[a,
b,d,g,h,k,l,r,m];e.params.returnType=t;e.params.returnBlob=t!=Dynamsoft.Enum_ReturnType.RT_BASE64;e.handleResult=c._handleImageData;c._addTask(e)});return e.promise}};Dynamsoft.Imagecore.prototype=Object.create(Dynamsoft.ImageIoBase.prototype);Dynamsoft.Imagecore.prototype.constructor=Dynamsoft.Imagecore;Dynamsoft.Imagecore.prototype.getImageFormat=function(a){var b=this,d=b._createTask("GetImageFormat");b._readFile(a,d).then(function(a){d.params.input=a;b._addTask(d)});return d.promise};
Dynamsoft.Imagecore.prototype.readImageInfo=function(a){var b=this,d=b._createTask("ReadImageInfo");b._readFile(a,d).then(function(a){d.params.input=a;b._addTask(d)});return d.promise};Dynamsoft.Imagecore.prototype.getMD5=function(a){var b=this,d=b._createTask("GetMD5");b._readFile(a,d).then(function(a){d.params.input=a;d.handleResult=function(a,b){return a.MD5};b._addTask(d)});return d.promise};Dynamsoft.Imagecore.prototype.getLicenseInfo=function(){return this._addTask(this._createTask("GetLicenseInfo"))};
Dynamsoft.Imagecore.prototype.getAesResult=function(a){return this._addTask(this._createTask("GetAesResult",[void 0!=a?a:""]))};Dynamsoft.Imagecore.prototype.saveImage=function(a,b,d,e){return this.saveImageInner(a,null,null,null,null,null,null,b,d,e)};
Dynamsoft.Imagecore.prototype.readImage=function(a,b,d,e){b=void 0!=b?b:this.outputType;d=void 0!=d?d:this.jpegQuality;e=void 0!=e?e:!1;var c=this,f=c._createTask("ReadImage");c._readFile(a,f).then(function(a){f.params.input=[a,b,d];f.params.returnType=e?Dynamsoft.Enum_ReturnType.RT_BASE64:Dynamsoft.Enum_ReturnType.RT_AUTO;f.params.returnBlob=!e;f.handleResult=c._handleImageData;c._addTask(f)});return f.promise};
Dynamsoft.Imagecore.prototype.openTiff=function(a){var b=this,d=b._createTask("LoadTiff");b._readFile(a,d).then(function(a){d.params.input=a;b._addTask(d)});return d.promise};
Dynamsoft.Imagecore.prototype.readTiff=function(a,b,d){a=void 0!=a?a:0;b=void 0!=b?b:this.outputType;d=void 0!=d?d:this.returnImageAsBase64;var e=this._createTask("ReadTiffPage");e.params.input=[a,b];e.params.returnType=d?Dynamsoft.Enum_ReturnType.RT_BASE64:Dynamsoft.Enum_ReturnType.RT_AUTO;e.params.returnBlob=!d;e.handleResult=this._handleImageData;return this._addTask(e)};Dynamsoft.Imagecore.prototype.closeTiff=function(){return this._addTask(this._createTask("EndReadTiff",null,this._handleBooleanResult))};
Dynamsoft.Imagecore.prototype.createTiff=function(){return this._addTask(this._createTask("NewTiff",null,this._handleBooleanResult))};Dynamsoft.Imagecore.prototype.appendImage=function(a,b,d,e){b=void 0!=b?b:this.inputType;d=void 0!=d?d:this.tiffFormat;e=void 0!=e?e:this.jpegQuality;var c=this,f=c._createTask("AppendImageToTiff");c._readFile(a,f).then(function(a){f.params.input=[a,b,d,e];f.handleResult=c._handleBooleanResult;c._addTask(f)});return f.promise};
Dynamsoft.Imagecore.prototype.addTag=function(a,b,d){return this._addTask(this._createTask("AddTagToNextPage",[a,b,void 0!=d?d:!1],this._handleBooleanResult))};Dynamsoft.Imagecore.prototype.getTiff=function(a){var b=this._createTask("GetTiffStream");b.handleResult=this._handleImageData;b.params.returnType=void 0!=a?a:Dynamsoft.Enum_ReturnType.RT_AUTO;b.params.returnBlob=a!=Dynamsoft.Enum_ReturnType.RT_AUTO;return this._addTask(b)};
Dynamsoft.Imagecore.prototype.getMemoryUsed=function(){return this._addTask(this._createTask("getMemoryUsed",null,function(a,b){return a.memoryUsed}))};Dynamsoft.Imagecore.prototype.getMultiPartFile=function(a,b){return this._addTask(this._createTask("ds_get_file",[a,b],function(a,b){return a}))};Dynamsoft.ImageProc=function(a,b,d){a=a?a:Dynamsoft.WasmEnv.productKey;Dynamsoft.ImageIoBase.call(this,a,Dynamsoft.WasmEnv.imgProc,b,d)};Dynamsoft.ImageProc.prototype=Object.create(Dynamsoft.ImageIoBase.prototype);
Dynamsoft.ImageProc.prototype.constructor=Dynamsoft.ImageProc;
Dynamsoft.ImageProc.prototype.initImage=function(a,b,d,e,c){b=void 0!=b?b:!1;d=void 0!=d?d:0;e=void 0!=e?e:0;c=void 0!=c?c:!1;var f=this,g=f._createTask("InitImageObject");g.params.input=[a,d,e];b||c?(b?g.params.input.push(Dynamsoft.Enum_ImageType.IT_RGBA):g.params.input.push(Dynamsoft.Enum_ImageType.IT_BGRA),f._addTask(g)):f._readFile(a,g).then(function(a){g.params.input[0]=a;g.params.input.push(Dynamsoft.Enum_ImageType.IT_ALL);f._addTask(g)});return g.promise};
Dynamsoft.ImageProc.prototype.rotate=function(a,b,d,e){a=void 0!=a?a:0;if(0>a||360<a)a%=360,0>a&&(a+=360);return this._addTask(this._createTask("RotateEx",[a,void 0!=d?d:!1,void 0!=e?e:3,void 0!=b?b:"FFFFFF"],this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.flip=function(a){a=void 0!=a?a:1;var b=this._createTask("");b.handleResult=this._handleBooleanResult;1===a?b.func="Flip":-1===a&&(b.func="Mirror");this._addTask(b);return b.promise};
Dynamsoft.ImageProc.prototype.erase=function(a,b,d,e,c){c=void 0!=c?c:"FFFFFF";var f=this._createTask("Erase");f.handleResult=this._handleBooleanResult;f.params.input=[a,b,d,e,c];this._addTask(f);return f.promise};Dynamsoft.ImageProc.prototype.crop=function(a,b,d,e){return this._addTask(this._createTask("Crop",[a,b,d,e],this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.resize=function(a,b,d){return this._addTask(this._createTask("ChangeImageSize",[a,b,void 0!=d?d:5],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.toGrayscale=function(a){a=void 0!=a?a:1;1>a&&(a=1);3<a&&(a=3);var b="";1===a?b="0":2===a?b="3;3;720;1.05":3===a&&(b="3;5;1080;1.05");return this._addTask(this._createTask("ConvertToGrayScale",b,this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.toBinary=function(a,b){b=void 0!=b?b:1;1>b&&(b=1);3<b&&(b=3);var d="";void 0!=a&&(a?d="1":1===b?d="0":2===b?d="2;3;720;1.05":3===b&&(d="2;5;1080;1.05"));return this._addTask(this._createTask("ConvertToBWScale",d,this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.invert=function(){return this._addTask(this._createTask("Invert",null,this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.setImageWidth=function(a,b){return this._addTask(this._createTask("SetImageWidth",[a,void 0!=b?b:"FFFFFF"],this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.setImageHeight=function(a,b){return this._addTask(this._createTask("SetImageHeight",[a,void 0!=b?b:"FFFFFF"],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.setDPI=function(a,b,d,e,c,f){return this._addTask(this._createTask("SetDPI",[a,b,d,e,void 0!=c?c:!1,f],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.getImage=function(a,b,d,e,c,f,g,h){a=void 0!=a?a:this.jpegQuality;b=void 0!=b?b:!0;e=void 0!=e?e:0;c=void 0!=c?c:0;f=void 0!=f?f:0;g=void 0!=g?g:!0;h=void 0!=d&&d&&void 0==h?Dynamsoft.Enum_ImageType.IT_JPG:void 0!=h?h:Dynamsoft.Enum_ImageType.IT_ALL;d=this._createTask("GetCurrentImage");d.params.input=[h,e,c,f,!1,a,b];d.params.returnBlob=g;d.handleResult=this._handleImageData;return this._addTask(d)};
Dynamsoft.ImageProc.prototype.getSkewAngle=function(a){return this._addTask(this._createTask("GetSkewAngle",[void 0!=a?a:""],function(a,d){return a.skewAngle}))};Dynamsoft.ImageProc.prototype.freeReservedData=function(){return this._addTask(this._createTask("FreeReservedData",null,this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.detectDocument=function(a,b,d,e,c){return this._addTask(this._createTask("DocumentDetect",[void 0!=a?a:2,(void 0!=b?b:75)/100,void 0!=d?d:100,(void 0!=e?e:0)/255,void 0!=c?c:""]))};Dynamsoft.ImageProc.prototype.perspective=function(a,b,d,e,c,f,g,h){return this._addTask(this._createTask("Perspective",[a,b,d,e,c,f,g,h],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.changeBrightness=function(a,b){a=void 0!=a?a:0;b=void 0!=b?b:1;0!=b&&1!=b&&(b=0);return 1===b?this._addTask(this._createTask("ChangeBrightnessAndContrast",[a,0],this._handleBooleanResult)):this._addTask(this._createTask("ChangeBrightness",[Math.floor(a/1E3*255)],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.changeContrast=function(a,b){a=void 0!=a?a:0;b=void 0!=b?b:1;0!=b&&1!=b&&(b=0);return 1===b?this._addTask(this._createTask("ChangeBrightnessAndContrast",[0,a],this._handleBooleanResult)):this._addTask(this._createTask("ChangeContrast",[1+a/1E3],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.removeShadow=function(a,b){a=void 0!=a?a:1;b=void 0!=b?b:1.05;1>a&&(a=1);3<a&&(a=3);var d="5";1===a?d+=";3;720;"+b:2===a?d+=";5;1080;"+b:3===a&&(d+=";10;0;"+b);return this._addTask(this._createTask("ShadowRemovel",[d],this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.enhanceAndSharpenImage=function(){return this._addTask(this._createTask("EnhanceAndSharpen",[""],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.brighten=function(){return this._addTask(this._createTask("Brighten",[""],this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.getBlurryScore=function(){return this._addTask(this._createTask("GetBlurScore",[""],function(a,b){return a.blurryScore}))};
Dynamsoft.ImageProc.prototype.drawQuadrangle=function(a,b,d,e,c,f,g,h,k,l){strParameter=(void 0!=k?k:"FFFFFF")+";"+(void 0!=l?l:5);return this._addTask(this._createTask("DrawQuadrangle",[a,b,d,e,c,f,g,h,strParameter],this._handleBooleanResult))};Dynamsoft.ImageProcWrapper={};
Dynamsoft.ImageProcWrapper.resize=function(a,b,d,e,c){var f=new Dynamsoft.ImageProc(Dynamsoft.WasmEnv.productKey);return f.initImage(a).then(function(){var a=void 0==c?5:c;var h=b>d?b/e:d/e;return f.resize(b/h,d/h,a)}).then(function(){return f.getImage()}).then(function(a){f.terminate();return a},function(a){f.terminate();return a})};
function rotatePoints(a,b,d,e){for(var c=[],f=0;f<a.length;f+=2){var g=a[f];var h=a[f+1];if(90==b)var k=d-h;else 180==b?(k=d-g,g=e-h):270==b?(k=h,g=e-g):(k=g,g=h);c.push(k,g)}return c}
Dynamsoft.ImageProcWrapper.createImage=function(a){var b,d,e,c,f,g,h,k,l,r,m,t,B,C,u,D,v,w,x,p,z,A,q,E,y;return $jscomp.asyncExecutePromiseGeneratorProgram(function(n){switch(n.nextAddress){case 1:b=new Dynamsoft.ImageProc(Dynamsoft.WasmEnv.productKey);n.setFinallyBlock(2);d={src:null,result:null,preview:null};e=a.source;c=a.output;f=e.imageWidth||e.width;g=e.imageHeight||e.height;h=e.imageData||e.data;if(void 0==c||void 0==c.orgImage&&void 0==c.previewImage)return n.return(d);k=void 0!=e.rgba?e.rgba:
!1;l=void 0!=e.bgra?e.bgra:!1;r=void 0!=a.doPerspective?a.doPerspective:!1;m=e.angle||0;return n.yield(b.initImage(h,k,f,g,l),4);case 4:t=n.yieldResult;d.src=t.srcBuffer;if(!r||!a.polygon){n.jumpTo(5);break}return n.yield(b.perspective(a.polygon.points[0],a.polygon.points[1],a.polygon.points[2],a.polygon.points[3],a.polygon.points[4],a.polygon.points[5],a.polygon.points[6],a.polygon.points[7]),5);case 5:if(0==m){n.jumpTo(7);break}if(0>m||360<m)m%=360,0>m&&(m+=360);return n.yield(b.rotate(m),7);case 7:if(!c.orgImage){n.jumpTo(9);
break}B=void 0==c.orgImage.returnBlob?!0:c.orgImage.returnBlob;C=void 0!=e.imageBitDepth?e.imageBitDepth:void 0;u=void 0!=e.imageXResolution?e.imageXResolution:void 0;D=void 0!=e.imageYResolution?e.imageYResolution:void 0;return n.yield(b.getImage(c.orgImage.quality,!1,k|l,C,u,D,B,c.orgImage.returnType),10);case 10:v=n.yieldResult,c.orgImage.returnType==Dynamsoft.Enum_ImageType.IT_BGRA?v.bgra=!0:c.orgImage.returnType==Dynamsoft.Enum_ImageType.IT_RGBA&&(v.rgba=!0),d.result=v;case 9:if(!c.previewImage){n.jumpTo(11);
break}w=f;x=g;if(90==m||270==m)w=g,x=f;p=Math.min(c.previewImage.width/w,c.previewImage.height/x);90==m||270==m?(z=Math.floor(g*p),A=Math.floor(f*p)):(z=Math.floor(f*p),A=Math.floor(g*p));return n.yield(b.resize(z,A,c.previewImage.nInterplationMethod),12);case 12:if(!a.polygon||r){n.jumpTo(13);break}q=a.polygon.points;0!=m&&(q=rotatePoints(q,m,w,x));return n.yield(b.drawQuadrangle(Math.floor(q[0]*p),Math.floor(q[1]*p),Math.floor(q[2]*p),Math.floor(q[3]*p),Math.floor(q[4]*p),Math.floor(q[5]*p),Math.floor(q[6]*
p),Math.floor(q[7]*p),a.polygon.strokeColor,a.polygon.lineWidth),13);case 13:return E=void 0==c.previewImage.returnBlob?!0:c.previewImage.returnBlob,n.yield(b.getImage(c.previewImage.quality,!0,k|l,void 0,void 0,void 0,E,c.previewImage.returnType),15);case 15:y=n.yieldResult,c.previewImage.returnType==Dynamsoft.Enum_ImageType.IT_BGRA?y.bgra=!0:c.previewImage.returnType==Dynamsoft.Enum_ImageType.IT_RGBA&&(y.rgba=!0),d.preview=y;case 11:return n.return(d);case 2:n.enterFinallyBlock(),b.terminate(),
n.leaveFinallyBlock(0)}})};Dynamsoft.PdfReader=function(a,b,d){a=a?a:Dynamsoft.WasmEnv.productKey;Dynamsoft.ImageIoBase.call(this,a,Dynamsoft.WasmEnv.pdfReader,b,d);this.resolution=200;this.readMode=3;this.outputType=Dynamsoft.Enum_ImageType.IT_ALL};Dynamsoft.PdfReader.prototype=Object.create(Dynamsoft.ImageIoBase.prototype);Dynamsoft.PdfReader.prototype.constructor=Dynamsoft.PdfReader;
Dynamsoft.PdfReader.prototype.open=function(a,b){b=void 0!=b?b:"";var d=this,e=d._createTask("LoadPdf");d._readFile(a,e).then(function(a){e.params.input=[a,b];e.handleResult=function(a,b){var c=Dynamsoft.base64Decode(a.infoBase64);try{try{c.replace(/\\/gi,"\\\\");var d=JSON.parse(c)}catch(l){d=c}return{PdfCount:a.pageCount,PdfInfo:d,isTextBased:a.isTextBased}}catch(l){b.reject({code:Dynamsoft.error.code.wasmJsInvalidJson,message:l.message,stack:l.stack})}};d._addTask(e)});return e.promise};
Dynamsoft.PdfReader.prototype.readPage=function(a,b,d,e,c,f){a=void 0!=a?a:0;b=void 0!=b?b:this.resolution;d=void 0!=d?d:this.readMode;e=void 0!=e?e:this.outputType;f=void 0!=f?f:this.returnImageAsBase64;c=void 0!=c?c:!1;var g=this._createTask("ReadPdfPage");g.params.input=[a,b,d,e,c];g.params.returnType=f?Dynamsoft.Enum_ReturnType.RT_BASE64:Dynamsoft.Enum_ReturnType.RT_AUTO;g.params.returnBlob=!f;g.handleResult=this._handleImageData;return this._addTask(g)};
Dynamsoft.PdfReader.prototype.close=function(){return this._addTask(this._createTask("UnloadPdf",null,this._handleBooleanResult))};Dynamsoft.PdfWriter=function(a,b,d){a=a?a:Dynamsoft.WasmEnv.productKey;Dynamsoft.ImageIoBase.call(this,a,Dynamsoft.WasmEnv.pdfWriter,b,d);this._setPdfSettings=function(a){var b={};if(void 0!=a&&"object"===typeof a)for(var d in a)b[d]=a[d];return b}};Dynamsoft.PdfWriter.prototype=Object.create(Dynamsoft.ImageIoBase.prototype);Dynamsoft.PdfWriter.prototype.constructor=Dynamsoft.PdfWriter;
Dynamsoft.PdfWriter.prototype.initPdfSetting=function(a){var b=this._createTask("InitPdfWriter");b.params.input=JSON.stringify(this._setPdfSettings(a));b.handleResult=this._handleBooleanResult;return this._addTask(b)};Dynamsoft.PdfWriter.prototype.appendPage=function(a){var b=this,d=b._createTask("AddPageFromImageFileStream");b._readFile(a,d).then(function(a){d.params.input=a;d.handleResult=b._handleBooleanResult;b._addTask(d)});return d.promise};
Dynamsoft.PdfWriter.prototype.writePdf=function(a){var b=this._createTask("GetPdfContent");b.params.returnType=void 0!=a?a:Dynamsoft.Enum_ReturnType.RT_AUTO;b.params.returnBlob=a!=Dynamsoft.Enum_ReturnType.RT_AUTO;b.handleResult=this._handleImageData;return this._addTask(b)};Dynamsoft.pdf=Dynamsoft.pdf||{};
Dynamsoft.pdf.IsModuleInstalled=function(){return Dynamsoft.isWasmSupport()?Dynamsoft.WasmEnv.pdfReader.status==Dynamsoft.conststring.initReady&&Dynamsoft.WasmEnv.pdfWriter.status==Dynamsoft.conststring.initReady:!1};
Dynamsoft.WasmEnv.getLicenseInfo=function(a,b,d){Dynamsoft.WasmEnv.productKey==a&&Dynamsoft.WasmEnv.licenseInfo?a=Promise.resolve(Dynamsoft.WasmEnv.licenseInfo):(Dynamsoft.WasmEnv.productKey=a,Dynamsoft.WasmEnv.licMode=void 0!=b?b?1:0:0,Dynamsoft.WasmEnv.uuid=void 0!=d?d:"",a=new Promise(function(a,b){var c=new Dynamsoft.Imagecore(Dynamsoft.WasmEnv.productKey);c.getLicenseInfo().then(function(b){c.terminate();Dynamsoft.WasmEnv.licenseInfo=b;a(b)},function(a){c.terminate();b(a)})}));return a};
Dynamsoft.WasmEnv.getWorkerPoolSize=function(){var a=Dynamsoft.WorkerPool.Instances;return a?a.length:0};Dynamsoft.WasmEnv.getMemoryUsed=function(){var a=Dynamsoft.WorkerPool.Instances;if(a){var b=[];a=$jscomp.makeIterator(a);for(var d=a.next();!d.done;d=a.next())d=d.value,d.terminated?b.push(0):b.push(d.getMemoryUsed());return b}return[]};
Dynamsoft.WasmEnv.getWasmNames=function(){for(var a=[],b=$jscomp.makeIterator(Dynamsoft.WasmEnv.moduleNames),d=b.next();!d.done;d=b.next())d=d.value,a.push(Dynamsoft.WasmEnv.buildWasmFileName(Dynamsoft.WasmEnv[d].prefixName,Dynamsoft.WasmEnv[d].ver,Dynamsoft.conststring.wasmExtension,!1));return a};
